version: '2'

services:
    web:
        image: lavoweb/php-7.4
        ports:
            - "10000:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db:db
    db:
        image: mysql:8.0
        container_name: my_mysql_container # Nom personnalisé
        ports:
            - "10002:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./docker-initdb:/docker-entrypoint-initdb.d # Répertoire pour le fichier SQL
        environment:
            - MYSQL_USER=spot # nom d'utilisateur
            - MYSQL_PASSWORD=spot-passwd # mot de passe utilisateur
            - MYSQL_DATABASE=dbSpotMinder
            - MYSQL_ROOT_PASSWORD=adminspotminder
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "10001:80"
        links:
            - db:db
