version: '2'

services:
    web:
        image: lavoweb/php-7.4
        ports:
            - "10000:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db:db
    db:
        image: mysql:8.0
        ports:
            - "10002:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=adminspotminder
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "10001:80"
        links:
            - db:db